server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://106.14.140.93:3306/njustc?useUnicode=true&characterEncoding=utf-8
    username: root
    password: lfm
    driver-class-name: com.mysql.cj.jdbc.Driver
